"""Redis Lua scripts for atomic inventory operations.

Single-source the Lua text here so the gRPC service and any future
tests both reference the exact same blob. SCRIPT LOAD is done once
per process; subsequent calls use EVALSHA.

The R11 rate-limiter (Step 8) uses the same pattern with its own
``bucket.lua`` — keep these two pieces stylistically aligned in the
report so the viva can describe one approach to "atomic compare-
and-decrement in Redis."
"""

# Reserve stock atomically across N variants with idempotency.
#
# Inputs:
#   KEYS[1]    = idempotency record key ("idem:reserve:{key}")
#   ARGV[1]    = candidate reservation_id (UUID4 generated by caller)
#   ARGV[2]    = user_id (string)
#   ARGV[3]    = reservation TTL seconds
#   ARGV[4]    = idempotency TTL seconds (typically longer)
#   ARGV[5..6] = variant_id, qty   (first item)
#   ARGV[7..8] = variant_id, qty   (second item)
#   ... pairs continue for each item
#
# Returns: a 3-element array
#   {1, "<existing_reservation_id>", ""}      — idempotent hit
#   {1, "<new_reservation_id>",      ""}      — first-time success
#   {0, "",                          "insufficient:<variant_id>"}
#                                              — first-time failure
#
# Atomicity: the whole script runs as a single Redis command, so the
# pre-check and the DECRBYs cannot interleave with another client.
# That makes a "rollback" step unnecessary — we only DECRBY once
# we've confirmed every variant has enough stock.
RESERVE_STOCK_LUA = """
local existing = redis.call('GET', KEYS[1])
if existing then
    return {1, existing, ""}
end

local n_items = (#ARGV - 4) / 2
local items = {}
for i = 1, n_items do
    items[i] = {
        vid = ARGV[3 + i * 2],
        qty = tonumber(ARGV[4 + i * 2])
    }
end

for _, it in ipairs(items) do
    local current = tonumber(redis.call('GET', 'stock:' .. it.vid))
    if not current or current < it.qty then
        return {0, "", "insufficient:" .. it.vid}
    end
end

for _, it in ipairs(items) do
    redis.call('DECRBY', 'stock:' .. it.vid, it.qty)
end

local res_key = 'reservation:' .. ARGV[1]
local hset_args = {res_key, 'user_id', ARGV[2], 'idem_key', KEYS[1]}
for _, it in ipairs(items) do
    table.insert(hset_args, 'v_' .. it.vid)
    table.insert(hset_args, tostring(it.qty))
end
redis.call('HSET', unpack(hset_args))
redis.call('EXPIRE', res_key, tonumber(ARGV[3]))

redis.call('SET', KEYS[1], ARGV[1], 'EX', tonumber(ARGV[4]))

return {1, ARGV[1], ""}
"""
